import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Grid,
  Typography,
} from "@material-ui/core";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { Product } from "./models";
import Link from "next/link";
import { GetServerSideProps, NextPage } from "next";
import http from "../http";

interface ProductsListPageProps {
  products: Product[]
}

// const products: Product[] = [
//   {
//     id: "1",
//     name: "My product 1",
//     description: "Very nice product",
//     price: 80.49,
//     image_url: "https://source.unsplash.com/800x600",
//     slug: "product-slug-here1",
//     created_at: "some date here",
//   },
//   {
//     id: "1",
//     name: "My product 1",
//     description: "Very nice product",
//     price: 80.49,
//     image_url: "https://source.unsplash.com/800x600",
//     slug: "product-slug-here2",
//     created_at: "some date here",
//   },
// ];

const ProductList: NextPage<ProductsListPageProps> = ({products}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Produtos</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
        Produtos
      </Typography>
      <Grid container spacing={4}>
        {products.map((product, index) => (
          <Grid key={index} item xs={12} sm={6} md={4}>
            <Card>
              <CardMedia
                style={{ paddingTop: "56%" }}
                image={product.image_url}
              />
              <CardContent>
                <Typography component="h2" variant="h5" gutterBottom>
                  {product.name}
                </Typography>
              </CardContent>
              <CardActions>
                <Link href="/products/[slug]" as={`/products/${product.slug}`} passHref>
                  <Button size="small" color="primary" component="a">
                    Detalhes
                  </Button>
                </Link>
              </CardActions>
            </Card>
          </Grid>
        ))}
      </Grid>
    </div>
  );
}

export default ProductList;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data: products } = await http.get('products');
  return {
    props: {
      products,
    }
  }
}